version: "3.5"

services:
  #
  consignment:
    restart: always
    build: ./consignment-service
    depends_on:
      - datastore
      - vessel
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"

  vessel:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"

  cli:
    build: ./consignment-cli

  datastore:
    image: mongo
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017
    command: mongod --logpath=/dev/null

  user:
    build: ./user-service
    ports: 
      - 50053:50051
    environment: 
      MICRO_ADDRESS: ":50051"

  database:
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: "password"
      POSTGGRES_USER: "admin"
    ports: 
      - 5432      
